name: restaurants_system
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  http: ^1.6.0
  flutter_riverpod: ^3.0.3
  cupertino_icons: ^1.0.8
  animated_toggle_switch: ^0.8.7
  google_nav_bar: ^5.0.7
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  intl_phone_number_input: ^0.7.5
  shared_preferences: ^2.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.7.1

  flutter_lints: ^5.0.0